name: Go2

on: 
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

#задания
jobs:
  #задание с идентификатором "build"
  build:
    # для запуска задания используется раннер "ubuntu-latest", что соответсвует последней версии ubuntu
    runs-on: ubuntu-latest
    # шаги задания
    steps:
    # первый шаг использует действие "actions/checkout@v3"
    # которое извлекает репозиторий для дальнейшей работы с ним
      - uses: actions/checkout@v3

    # шаг с именем "Set up Go"
      - name: Set Up Go
      # этот шаг использует действие "actions/setup-go@v4", которое установит Go в систему
        uses: actions/setup-go@v4
      # для этого действия можно задать версию Go, которую надо установить
        with:
          go-version: '1.26'

      # шаг с именем "Build"
      - name: Build
        # Этот шаг просто выполняет команду go build -v ./...
        run: go build -v ./...
      
      # шаг с именем Test
      - name: Test
        # Этот шаг выполняет команду go test -v ./...
        run: go test -v ./...